language: java
jdk:
- oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script: 
- "./gradlew test"
- "./gradlew quarkusBuild --uber-jar"
deploy:
  provider: elasticbeanstalk
  zip_file: 'build/quarkus-lab-runner.jar'
  access_key_id: $ACCESSKEYID
  secret_access_key: $ACCESSKEYSECRET
  region: eu-west-1
  app: quarkus-lab
  env: quarkus-lab-environment
  bucket_name: ci-deploy-bucket
  skip_cleanup: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN="c4f1e0d8-b382-444a-a475-ce25d6f97cb7"
  - secure: FBCDYx8Znk3ik+19kPQaopSO3zlXi67dTXm826FM4l3CJX6aR4kX0FZBANldXWcua4aCdVevcDWDNAFcb997Q83hgUmiD7xssku6oXaYV1GxoMEdziUMra+v1TMZxb9Jp5wEvszC/NB0ZPpWlosLIbRNTbQKqvNI0SrCUDKOYf2v5PuLTCjRBordeFW4dwbArhbdA7QtxUrWmk+yF7CECKPbFeAxv7sglph09JDc+f2rDIxYm2vi1Jr6SIedsJ/+GW+U2Ljqz27XcNguq8Rzaty93mM4ytIVMKREJR1XBP6I6bAtA4u3SFQT7UJAF+eC2HUJ9PbH6U4yQhjgL2Hz/rn7ITnuL93ccRGzpZNEhQvHdiI67qJ78bBlwPAYDiT2jnSmhDsPEhUpmCvY6rzgS7M/zDMRjB4uBH+LkZUTd81gR3iH0qG2bpOYN3wcgo8x5R3Y73D1qRZ5Cw1E6cxIMnS9JlAWoCofiY3xKovKYSVmzgbNEmYDpYFKzp7iksVrN+rEThcveO7TOMc0AFLyb+xl8EItvUhgMOHG7d9ZZBkKZ5BOVFvcIwssR6MaJdj1GAgXCDbL9uXxnl7lxFDnymEFR0BC2Phxmfd+sO4tV9lj7Wis+z5uG2psVevMecXSA8z7LfozbzpxuqVWR7OKU/1G5Ef6XYH+Kw0QUpF/V0w=
  - secure: J63StPD+dMvpiBmuQ1LIqt6Z/1fREi7qSeN5v/jSQihgHydgKa39pwThd1KBPFT8RDVnjkQcC/4CLoZaY9eq1+sF80FRcViGVSLbAKrVXjH2zkwR7a4oKo+MSay7vqk0LITK1PjTsOw6gKA/fEGqiTA1thERKgDqureEvwYB/MlZjVlhM1A5OKdl3U0inyfMcYGJlam8FbhqsUxNlZREVx2UV/jzReNCoNpN5tmb/ePdhhGqmGWCH7b40+5IAqvYLIsITgJFV9sI03hQVFwypxQohjISrOaTZtwiTTH15i1chEl4bJP5zEWPr8u4LAA+4eyg2VGyBcHkflP3qepMBJ/NV4Igew9Sa3jLMu0nzH15Y/srKGCDOznimgDLzDE7nW8WDWe7o0sGJLq+24xKMoCXZvjkL8PioVGpwBdafAHPDkuyEjRBI8i0/Y1wM+phvFPkGdk9qOQukpcof9cHfIPcSi/8ryDk8CaPzfCDhQfQphgm0X28fPYwe5jR7ceFpZYDfz+RqUl8VaTXzhUrTfKOlmgKPJdbiYARVZsF7Wu6vOQC07JIkfaHE2JkESSlw4oEbXyR6xWCPoPdHNK0nYmJJ2XFbzkZeL1QPT3Ws0EVQ5xGzGfHixrVoLynswkM8uV/8BHldVOIeoQO3lP3dLE1dKDQvjJMY8D2rh5OAy8=
